query QDevArticle($slug: String!) {
    blog(filter: { slug: { _eq: $slug } }) {
        id
        status
        title
        date_created
        slug
        elements {
            item {
                ... on blog_image {
                    id
                    caption
                    image {
                        id
                        filename_disk
                    }
                }
                ... on blog_text {
                    text
                    id
                }
                ... on blog_title {
                    title
                    level
                    tag
                    id
                }
                ... on blog_quote {
                    id
                    text
                    author
                    url
                }
                ... on blog_map {
                    id
                }
                ... on blog_video {
                    id
                    url
                }
            }
            collection
        }
    }
}
