query QMap {
    place(limit: -1) {
        id
        location
        translations {
            id
            name
            languages_code {
                abbreviation
            }
        }
        country {
            id
            translations {
                id
                name
                currency
                languages_code {
                    abbreviation
                }
            }
        }
    }
    transportation(limit: -1) {
        id
        type
        company
        number
        vessel
        departure_airport_code
        arrival_airport_code
        departure
        arrival
        show_time
        from {
            id
            location
            country {
                id
                translations {
                    id
                    name
                    languages_code {
                        abbreviation
                    }
                }
            }
            translations {
                id
                name
                languages_code {
                    abbreviation
                }
            }
        }
        to {
            id
            location
            country {
                id
                translations {
                    id
                    name
                    languages_code {
                        abbreviation
                    }
                }
            }
            translations {
                id
                name
                languages_code {
                    abbreviation
                }
            }
        }
    }
}
